# Generated by Django 4.2.2 on 2023-06-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='first',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='flights',
            field=models.ManyToManyField(blank=True, default='', related_name='passengers', to='flights.flight'),
        ),
    ]
